### ISSUE TITLE
api not starting

### ISSUE THREAD

**Issue by NickWarlock** [blaisewf/rvc-cli#81]
After executing env/python.exe rvc_cli.py api it outputs an error:

An error occurred during execution: expected str, bytes or os.PathLike object, not int
Traceback (most recent call last):
  File "H:\rvc\rvc-cli\rvc_cli.py", line 1736, in main
    run_api_script(
  File "H:\rvc\rvc-cli\rvc_cli.py", line 608, in run_api_script
    subprocess.run(command)
  File "H:\rvc\rvc-cli\env\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "H:\rvc\rvc-cli\env\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "H:\rvc\rvc-cli\env\lib\subprocess.py", line 1360, in _execute_child
    args = list2cmdline(args)
  File "H:\rvc\rvc-cli\env\lib\subprocess.py", line 565, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "H:\rvc\rvc-cli\env\lib\os.py", line 822, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not int

**Comment by blaisewf** [comment]
api mode isnt available, you can build one using the cli
