### ISSUE TITLE
[Q&A] What should I do with hybrid?

### ISSUE THREAD

**Issue by ytoaa** [blaisewf/rvc-cli#82]
C:\Users\gas\Documents\AIproject-sub\rvc-cli>env\python.exe rvc_cli.py infer --input_path "C:\Users\gas\Documents\AIproject-sub\rvc-cli\raw\1.wav" --output_path "C:\Users\gas\Documents\AIproject-sub\rvc-cli\output\test4.wav"
 --pth_path "C:\Users\gas\Documents\AIproject-sub\rvc-cli\raw\IUs_KLM\IUs_KLM.pth" --index_path "C:\Users\gas\Documents\AIproject-sub\rvc-cli\raw\IUs_KLM\IUs_KLM.index" --f0_method "hybrid[crepe+rmvpe+fcpe]" --pitch 12
Converting audio 'C:\Users\gas\Documents\AIproject-sub\rvc-cli\raw\1.wav'...
Calculating f0 pitch estimations for methods ['crepe', 'rmvpe', 'fcpe']
An error occurred during audio conversion: 'Pipeline' object has no attribute 'get_f0_crepe_computation'
Traceback (most recent call last):
  File "C:\Users\gas\Documents\AIproject-sub\rvc-cli\rvc\infer\infer.py", line 463, in convert_audio
    audio_opt = self.vc.pipeline(
  File "C:\Users\gas\Documents\AIproject-sub\rvc-cli\rvc\infer\pipeline.py", line 582, in pipeline
    pitch, pitchf = self.get_f0(
  File "C:\Users\gas\Documents\AIproject-sub\rvc-cli\rvc\infer\pipeline.py", line 351, in get_f0
    f0 = self.get_f0_hybrid(
  File "C:\Users\gas\Documents\AIproject-sub\rvc-cli\rvc\infer\pipeline.py", line 262, in get_f0_hybrid
    f0 = self.get_f0_crepe_computation(
AttributeError: 'Pipeline' object has no attribute 'get_f0_crepe_computation'

It works when you have three of them separately, but the hybrid doesn't.

**Comment by blaisewf** [comment]
i’ll fix, but just use rmvpe

**Comment by blaisewf** [comment]
fixed, ill push it soon
